### ISSUE TITLE
ErgoScript contracts

### ISSUE THREAD

**Issue by jasondavies** [anon-real/ErgoAuctionHouse#1]
Congratulations on getting this out there!

I couldn't find the ErgoScript contracts used to generate the P2S addresses.  Can you publish these?

**Comment by anon-real** [comment]
Thanks. Will post the technical details on the forum soon.
Very similar to the discussion here though: https://www.ergoforum.org/t/auctions-on-ergo/122

**Comment by anon-real** [comment]
You can find some details here: https://github.com/ergoplatform/ergo/issues/1217
Please let me know there if any more info is needed.
