### ISSUE TITLE
Get auctions list from the backend

### ISSUE THREAD

**Issue by pyotrsky** [anon-real/ErgoAuctionHouse#45]
Should get the list of auctions from the backend instead of contacting the explorer directly.

- [ ] Active auctions list by lowest remaining time
- [ ] Active auctions list by highest remaining time
- [ ] Active auctions list by lowest bid
- [ ] Active auctions list by highest bid
- [ ] Active auctions list by hottest first
- [ ] Active auctions list by my auctions first
- [ ] Active auctions list by my bids first
- [ ] Active auctions list by ERG auctions first
- [ ] Active auctions list by non ERG auctions first
- [ ] Past auctions page
- [ ] My auctions (Owned) page

**Comment by 11001101110101110001111010111110101** [comment]
I am implementing the mentioned back-end services with express js.
