### ISSUE TITLE
Misleading Yoroi Wallet non support information

### ISSUE THREAD

**Issue by veriumfellow** [anon-real/ErgoAuctionHouse#8]
Update Wallet > Yoroi Wallet > shows "Support for Yoroi will be added in the future." although when we click on "Any Wallet", it works with the Yoroi Wallet. So the information is potentially turning off potential buyers. Either remove Yoroi Wallet, or use the same information as under Any Wallet; or change title to "Any Wallet 'including Yoroi)"

**Comment by anon-real** [comment]
Fixed!
