### ISSUE TITLE
"No active auctions" on main page

### ISSUE THREAD

**Issue by veriumfellow** [anon-real/ErgoAuctionHouse#9]
https://ergoauctions.org/#/auction/active => shows no active auctions. A new user could just leave the page thinking that nothing is going on here. This page should either list the NFT categories or just show the picture NFTs as it's the biggest category.

**Comment by sepehr2github** [comment]
Thanks for reporting issue, I'm working on it.

**Comment by anon-real** [comment]
Fixed.
